port to substrate3.0
xlc/orml-workshop pull request #4
Opened 2021-05-11 02:12 UTC by baidang201

Closes #3

2021-05-11 02:57 UTC, xlc requested changes

2021-05-11 02:57 UTC, xlc commented on pallets/exchange/src/lib.rs
> +				.unwrap_or(());
这个不对，交易失败就不再报错了

2021-05-11 02:57 UTC, xlc commented on pallets/exchange/src/lib.rs
> +			Orders::<T>::try_mutate_exists(order_id, |order| -> DispatchResultWithPostInfo {
```suggestion
			Orders::<T>::try_mutate_exists(order_id, |order| -> DispatchResult {
```

然后都用 `Ok(())` 就好了

2021-05-11 02:57 UTC, xlc commented on pallets/exchange/src/lib.rs
> +		#[pallet::weight(10_000)]
```suggestion
		#[pallet::weight(10_000)]
		#[transactional]
```

然后就没有 `with_transaction_result` 的必要了

2021-05-11 13:27 UTC, baidang201 commented on pallets/exchange/src/lib.rs
> +				.unwrap_or(());
fix

2021-05-11 13:27 UTC, baidang201 commented on pallets/exchange/src/lib.rs
> +			Orders::<T>::try_mutate_exists(order_id, |order| -> DispatchResultWithPostInfo {
fixed

2021-05-11 13:28 UTC, baidang201 commented on pallets/exchange/src/lib.rs
> +		#[pallet::weight(10_000)]
fix

2021-05-13 00:17 UTC, baidang201 commented
已修复审查的问题，在看看

2021-05-13 02:09 UTC, merged

2021-05-13 02:10 UTC, xlc commented
感谢🙏